### ISSUE TITLE
vcpu number bigger than 64

### ISSUE THREAD

**Issue by shiguowang** [tenclass/mvisor#37]
Our program requires a virtual machine with more than 64 cores, but currently only a maximum of 64 cores can be configured. [nooodles2023](https://github.com/nooodles2023)pointed out that the code can be modified to achieve this.Those who need it can refer to it.modify file virtio_pci.h
std::array<VirtQueue, 64>   queues_; chang to std::array<VirtQueue, 128>   queues_;

**Comment by 78** [comment]
Thank you for the information, we will adjust this limitation in future versions.
