### ISSUE TITLE
How to share host folder to guest?

### ISSUE THREAD

**Issue by brookate** [tenclass/mvisor#40]
I'm using windows guest, but how to share files to guest? is there any way like virtualbox ?

**Comment by nooodles2023** [comment]
Of course you need to add the part of config and install virtio-fs driver in guest.
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

**Comment by shiguowang** [comment]
If the guest system is rocky linux, do I still need to install virtio-fs driver? @nooodles2023

**Comment by nooodles2023** [comment]
> If the guest system is rocky linux 9.0, do I still need to install virtio-fs driver? @nooodles2023

I haven't test virtio-fs on rocky linux guest, but it shoud work. Try mount the path in guest like this:
mount -t virtiofs mount_tag /mnt/mount/path
"mount_tag" should be replaced with the value of config "disk_name" in viritio-fs

**Comment by brookate** [comment]
> > If the guest system is rocky linux 9.0, do I still need to install virtio-fs driver? @nooodles2023
> 
> I haven't test virtio-fs on rocky linux guest, but it shoud work. Try mount the path in guest like this: mount -t virtiofs mount_tag /mnt/mount/path "mount_tag" should be replaced with the value of config "disk_name" in viritio-fs

It's also support for windows ?

**Comment by nooodles2023** [comment]
> > > If the guest system is rocky linux 9.0, do I still need to install virtio-fs driver? @nooodles2023
> > 
> > 
> > I haven't test virtio-fs on rocky linux guest, but it shoud work. Try mount the path in guest like this: mount -t virtiofs mount_tag /mnt/mount/path "mount_tag" should be replaced with the value of config "disk_name" in viritio-fs
> 
> It's also support for windows ?

Yes

**Comment by brookate** [comment]
How? I can't found any info in windows guest.

**Comment by brookate** [comment]
Oh, I find it. 
https://docs.redhat.com/zh_hans/documentation/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/sharing-files-between-the-host-and-its-virtual-machines-using-virtio-fs_sharing-files-between-the-host-and-its-virtual-machines

**Comment by shiguowang** [comment]
> > If the guest system is rocky linux 9.0, do I still need to install virtio-fs driver? @nooodles2023
> 
> I haven't test virtio-fs on rocky linux guest, but it shoud work. Try mount the path in guest like this: mount -t virtiofs mount_tag /mnt/mount/path "mount_tag" should be replaced with the value of config "disk_name" in viritio-fs

It works !
![image](https://github.com/user-attachments/assets/cddf8b99-5132-4d37-bf51-8744c60a7d2d)
