### ISSUE TITLE
Sooo I'm having the same issue that happened with @bondlei (the person who asked about vgpu support and was unable to compile the code)

### ISSUE THREAD

**Issue by devtinoimao** [tenclass/mvisor#48]
Same issue, Same error, Almost everything the same, but how do I solve it? I'm not a code expert I'm just a scratch/godot expert and idk should I like compile virgl and `ninja install` virglrenderer?

I will update you all if I'm able to solve this issue

EDIT: I actually solved it imao issue closed

**Comment by jobs-git** [comment]
Be kind to at least elaborate your solution for the next person who might have similar issues
