### ISSUE TITLE
RX5700 gpu passthrough not working

### ISSUE THREAD

**Issue by Allegorii** [tenclass/mvisor#55]
![image](https://github.com/user-attachments/assets/044c243e-c7cd-4b1c-ae2a-158b082748fb)
直通rx5700在系统里面无法正常使用，系统是win11 22h2，使用win10 ltsc也是一样的效果

**Comment by Allegorii** [comment]
![image](https://github.com/user-attachments/assets/9e94b42e-036a-42a4-a408-a5155b78c0e3)
进入系统显卡会显示错误43，禁用再启用会显示设备运转正常，但实际无法使用

**Comment by Allegorii** [comment]
使用qemu的时候也曾经有过同样的情况，当时是关闭rebar解决，刚才在bios发现rebar的确是关闭的，打开后mviosr是直接无法启动，终端显示
[0.501] core/pci_device.cc:410 SetupPciBar64() panic-error: Assertion failed, size <= 1ULL << 32 errno=2, No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Panic

**Comment by 78** [comment]
可以看看 vfio 的配置吗？ 现在很多显卡都有HDA，要把 Display 和 HDA 两个 pci 都 passthrough，才不会出现 43 错误。rebar 看情况是要关闭的。

**Comment by Allegorii** [comment]
[sample.txt](https://github.com/user-attachments/files/17146101/sample.txt)
[vfio.txt](https://github.com/user-attachments/files/17146126/vfio.txt)
这是我的mvisor配置和vfio配置，不过现在使用的是一张6800xt，同样也失败了

**Comment by Allegorii** [comment]
用virt-manager新开了一个虚拟机把显卡直通进去能正常运行
![image](https://github.com/user-attachments/assets/aa5ba11a-9609-43e0-9983-663214bdd554)
可以看到也是有可以负载的
![image](https://github.com/user-attachments/assets/7e12d4f1-128f-4173-ab2b-43aa02872f10)
任务管理器和gpuz也是能正常识别的，所以应该不是硬件的问题

**Comment by 78** [comment]
> 使用qemu的时候也曾经有过同样的情况，当时是关闭rebar解决，刚才在bios发现rebar的确是关闭的，打开后mviosr是直接无法启动，终端显示 [0.501] core/pci_device.cc:410 SetupPciBar64() panic-error: Assertion failed, size <= 1ULL << 32 errno=2, No such file or directory terminate called after throwing an instance of 'std::runtime_error' what(): Panic

这个错误会在最近几天的版本更新中修复，是因为代码没有支持大于4GB的pci映射空间导致。

**Comment by nooodles2023** [comment]
@Allegorii https://github.com/tenclass/mvisor/pull/66

**Comment by nooodles2023** [comment]
> ![image](https://private-user-images.githubusercontent.com/47803195/370703527-9e94b42e-036a-42a4-a408-a5155b78c0e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjM3NDIsIm5iZiI6MTczMTMyMzQ0MiwicGF0aCI6Ii80NzgwMzE5NS8zNzA3MDM1MjctOWU5NGI0MmUtMDM2YS00MmE0LWE0MDgtYTUxNTViNzhjMGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZTI1OTU0YTExNWFmNGZlMjAzNzFhZjM3NjI4YTI2MzMwNTdlNTQ1M2RkODNiMmE4YzlkOWIxYjQ5MDFmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uti7gH7hdpJlFzBNjy1nyGt-Kxyivt_Se3C7FJl-WpA) 进入系统显卡会显示错误43，禁用再启用会显示设备运转正常，但实际无法使用 另外使用root权限才能把显卡直通进去，此时声音会失效，终端显示 [0.001] gui/sdl/viewer.cc:265 OnPlayback() warn: snd_pcm_open error: Host is down

不用root启动想要passthrough可以参考这个
https://www.evonide.com/non-root-gpu-passthrough-setup/#Permissions_for_non-root_GPU_passthrough
简单点可以直接修改对应vfio设备的权限，然后改一下内存限制即可
```
/etc/security/limits.conf
qemu_vga soft memlock 20000000
qemu_vga hard memlock 20000000
```
