### ISSUE TITLE
issue during compilation

### ISSUE THREAD

**Issue by limbo127** [tenclass/mvisor#56]
Hello, 
When I try to compile,
 meson setup build -Dsdl=true

(

Project version: 2.7.2
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240910")
C linker for the host machine: cc ld.bfd 2.43.0
C++ compiler for the host machine: c++ (gcc 14.2.1 "c++ (GCC) 14.2.1 20240910")
C++ linker for the host machine: c++ ld.bfd 2.43.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

I obtain : 
cc1: error: command-line option ‘-Wnon-virtual-dtor’ is valid for C++/ObjC++ but not for C [-Werror]

Nicolas

**Comment by 78** [comment]
Is there any mention of which line of code has this error?

**Comment by limbo127** [comment]
for example 
[100/176] Compiling C object mvisor.p/devices_display_qxl_canvas_canvas_utils.c.o
FAILED: mvisor.p/devices_display_qxl_canvas_canvas_utils.c.o 
cc -Imvisor.p -I. -I.. -I../include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pixman-1 -I/usr/include/SDL2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -O2 -g -Wno-unused-parameter -DPROTOBUF_USE_DLLS -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -DNOMINMAX -D_REENTRANT -pthread -MD -MQ mvisor.p/devices_display_qxl_canvas_canvas_utils.c.o -MF mvisor.p/devices_display_qxl_canvas_canvas_utils.c.o.d -o mvisor.p/devices_display_qxl_canvas_canvas_utils.c.o -c ../devices/display/qxl/canvas/canvas_utils.c
cc1: error: command-line option ?-Wnon-virtual-dtor? is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
[101/176] Compiling C object mvisor.p/devices_display_qxl_canvas_lines.c.o




all build seem to be flood : 
build mvisor.p/gui_keymap.c.o: c_COMPILER ../gui/keymap.c || mvisor.p/ac97.pb.h mvisor.p/ahci_host.pb.h mvisor.p/apple_smc.aml mvisor.p/apple_smc.hex mvisor.p/ata_cdrom.pb.h mvisor.p/cmos.pb.h mvisor.p/cpu_container.aml mvisor.p/cpu_container.hex mvisor.p/firmware_config.aml mvisor.p/firmware_config.hex mvisor.p/firmware_config.pb.h mvisor.p/hda_duplex.pb.h mvisor.p/i440fx.aml mvisor.p/i440fx.hex mvisor.p/i82078_fdc.pb.h mvisor.p/i8257_dma.pb.h mvisor.p/ich9_hda.pb.h mvisor.p/ich9_lpc.pb.h mvisor.p/ide_host.pb.h mvisor.p/io_thread.pb.h mvisor.p/memory_manager.pb.h mvisor.p/pci_device.pb.h mvisor.p/pci_host.pb.h mvisor.p/piix3.pb.h mvisor.p/piix4_pm.pb.h mvisor.p/pmio.pb.h mvisor.p/ps2.pb.h mvisor.p/pvpanic.aml mvisor.p/pvpanic.hex mvisor.p/q35.aml mvisor.p/q35.hex mvisor.p/qxl.pb.h mvisor.p/uhci_host.pb.h mvisor.p/usb_device.pb.h mvisor.p/vcpu.pb.h mvisor.p/vga.pb.h mvisor.p/virtio_console.pb.h mvisor.p/virtio_pci.pb.h mvisor.p/xhci_host.pb.h
 DEPFILE = mvisor.p/gui_keymap.c.o.d
 DEPFILE_UNQUOTED = mvisor.p/gui_keymap.c.o.d
 ARGS = -Imvisor.p -I. -I.. -I../include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pixman-1 -I/usr/include/SDL2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -O2 -g -Wno-unused-parameter -DPROTOBUF_USE_DLLS -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -Wnon-virtual-dtor -DNOMINMAX -D_REENTRANT -pthread

**Comment by limbo127** [comment]
same as #49
