### ISSUE TITLE
leak for block storage ?

### ISSUE THREAD

**Issue by limbo127** [tenclass/mvisor#57]
Hello, 
How use a device block as qemu ( -blockdev '{"driver":"host_device","filename":"/dev/sda","aio":"native" ) 
or as libvirt def
<disk type='block' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native' discard='unmap'/>
      <source dev='/dev/sda'/>
      <target dev='vda' bus='virtio'/>
    </disk>

Regards, 
Nicolas

**Comment by 78** [comment]
This thing hasn't been tried out yet. If needed, you can mess around with the code and make it fit on your own. It ain't that super hard.

**Comment by limbo127** [comment]
I'm not developer, i'm trying with an image but at my work, we are using block device or iscsi as semu block
Thanks

**Comment by limbo127** [comment]
Fix with #63
