### ISSUE TITLE
network and hostfile access configuration

### ISSUE THREAD

**Issue by woecj** [tenclass/mvisor#8]
Hi,
I installed windows 10 on mvisor. guest os is running and has internet access, but no access to local host. Also, no access to host file system.
How to configure access to local network and host file system?

woecj

**Comment by nooodles2023** [comment]
For host file system, you could use virtio-fs device, there is a config sample in sample.yaml.
For local network, mvisor only support UIP as backend network now, you could map the port from guest to host.

**Comment by woecj** [comment]
Ok, thank you for the answer.
But can you give me some info on the syntax of the yaml file to make these entries.
There is no documents for that, so I have problems to make them.
Thanks

**Comment by nooodles2023** [comment]
- class: virtio-fs
    path: /tmp/fuse
    disk_name: mvisor-fs
    disk_size: 2G
    inode_count: 200
disk_size is the config of virtio-fs disk total size for guest vm, inode_count is the limit of total file count in virtio-fs disk.
if you want to map an existing directory, make sure the disk_size and inode_count are bigger than them in the directory.

  - class: virtio-network
    mac: 00:50:00:11:22:33
    map: tcp:0.0.0.0:8022-:22
Here is an example of port map. It maps the port 22 in guest vm to host 8022.

**Comment by nooodles2023** [comment]
the mvisor-fs disk would appear when you install virtio-fs guest driver, for more information, check https://virtio-fs.gitlab.io/.
buddy, local network was not accessible because we only implemented UIP, the only way you can try was mapping port, it will help you access port in vm from host or redirect url in guest to another

**Comment by woecj** [comment]
ok, fs access running now.

Is there any source for configuring uiP stack for amd64 machine?

**Comment by 78** [comment]
@woecj uip is the default stack for virtio-network device. You don't need to do any further configuration. Just one line is enough:
```
     -class: virtio-network
```

uip creates a NAT for the VM to access the internet. I'm sure you can access the host local network from the guest OS.

**Comment by woecj** [comment]
You are right. Seems starting the virtio-fs service in the vm also started the virtio-network
Access to local network ok now
Thanks!
